# Generated by Django 4.1.7 on 2023-03-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_categorie_produit_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='libellé',
            field=models.CharField(choices=[('al', 'alimentaire'), ('mb', 'meuble'), ('vs', 'vaisselle'), ('sn', 'sanitaire'), ('vt', 'vetement'), ('jx', 'jouets'), ('lg', 'linge de maison'), ('bj', 'bijoux'), ('dc', 'decor')], default='al', max_length=50),
        ),
    ]
