# Generated by Django 4.1.7 on 2023-03-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_fournisseur_produit_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='adresse',
            field=models.TextField(default='Non définie'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(default='Non définie', max_length=254),
        ),
    ]
